# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: crypto_amazon_indexer
networks:
  - id: 11155420
    start_block: 0
    contracts:
      - name: Storefront
        address:
          - 0xf2F5F769509065DFdfe9f31E440F3f94e9F7c21b
        handler: src/EventHandlers.ts
        events:
          - event: ProductListed(string asin, address seller, uint256 price)
rollback_on_reorg: false
